Error: object 'dat' not found 
Traceback: 
[1] "4: pull(dat, Attribute_group) at #4"     "3: {"                                   
[3] "       function(y) y[!is.na(y)]"         "   }(pull(dat, Attribute_group))"       
[5] "2: unique({"                             "       function(y) y[!is.na(y)]"        
[7] "   }(pull(dat, Attribute_group))) at #2" "1: myFun(dat)"                          
